apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "info.name" . }}
  namespace: {{default "affise" .Values.global.namespace}}
  labels:
    app: {{ template "info.name" . }}
    chart: {{ template "info.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "info.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "info.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          - /info
          args:
{{ toYaml .Values.args | indent 12 }}
          env:
          {{- range $key, $value := .Values.env }}
          - name: {{ $key }}
            value: {{ $value }}
          {{- end }}
          ports:
          - name: {{ .Values.grpcPortname }}
            containerPort: {{ .Values.grpcPort }}
          - name: {{ .Values.mgmntPortname }}
            containerPort: {{ .Values.mgmntPort }}
          volumeMounts:
            - name: data
              mountPath: /data
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
          livenessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 40
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
